version: "3"

services:
  # KAFKA RELATED SERVICES

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - '2182:2181'
  kafka:
    image: 'wurstmeister/kafka:2.12-2.2.1'
    ports:
      - '9092:9092'
      - '1099:1099'
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_MESSAGE_MAX_BYTES: 10485760
      KAFKA_CREATE_TOPICS: 'test_topic:1'
      JMX_PORT: '1099'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
  consumer:
    image: ru.kafka.consumer:latest
    ports:
      - '8080:8080'
    environment:
      KAFKA_HOST: kafka:9092
    links:
      - 'kafka'
  producer:
    image: ru.kafka.producer:latest
    ports:
      - '8090:8080'
    environment:
      KAFKA_HOST: kafka:9092 
    links:
      - 'kafka'   

